---
0x00:
    name: Vendor_ID
    width: 2
    subField: null
    attribute: RO
0x02: 
    name: Device_ID
    width: 2
    subField: null
    attribute: RO
0x04:
    name: command
    width: 2
    subField:
        0:
            name:  IO_Space
            width: 1
            default: 0
            attribute: RW
        1:
            name: Memory_Space_Accesses
            width: 1
            default: 0
            attribute: RW
        2:
            name: Bus_Master
            width: 1
            default: 0
            attribute: RW
        3:
            name: Special_Cycles
            width: 1
            default: 0
            attribute: RW
        4:
            name: emory_write_and_Invalidate_enable
            width: 1
            default: 0
            attribute: RW
        5:
            name: GA_Palette_Snoop
            width: 1
            default: 0
            attribute: RW
        6:
            name: Parity_Error_Response
            width: 1
            default: 0
            attribute: RW
        7:
            name: Reserved
            width: 1
        8:
            name: SERR_N_enable
            width: 1
            default: 0
            attribute: RW
        9:
            name: Fast_Back_to_Back_Enable
            width: 1
            default: 0
            attribute: RW
        10:
            name: Interrupt_Disable
            width: 1
            default: 0
            attribute: RW
        11:
            name: Reserved
            width: 5
    attribute: null
0x06:
    name: status
    width: 2
    subField:
        0:
            name: Reserved
            width: 3
        3:
            name: Interrupt_List
            width: 1
            default: 0
            attribute: RO
        4:
            name: Capabilities_List
            width: 1
            default: 0
            attribute: RO
        5:
            name: 66MHz_Capable
            width: 1
            default: 0
            attribute: RO
        6:
            name: Rewerved
            width: 1
        7:
            name: Fast_Back-to-Back_Capable
            width: 1
            default: 0
            attribute: RO
        8:
            name: Master_Data_Paritty_Error
            width: 1
            default: 0
            attribute: RO
        9:
            name: DEVSEL_Timing
            width: 2
            default: 00
            attribute: RO
        11:
            name: Signaled_Target_Abort
            width: 1
            default: 0
            attribute: RO
        12:
            name: Received_Target_Abort
            width: 1
            default: 0
            attribute: RO
        13:
            name: Received_Master_Abort
            width: 1
            default: 0
            attribute: RO
        14:
            name: Signaled_System_Error
            width: 1
            default: 0
            attribute: RO
        15:
            name: Detected_Parity_Error
            width: 1
            default: 0
            attribute: RO
    attribute: null
0x08:
    name: Revision_ID
    width: 1
    subField: null
    attribute: RO
0x07:
    name: Class_Code
    width: 3
    subField: null
    attribute: RO
0x0C:
    name: Cacheline_size
    width: 1
    subField: null
    attribute: RO
0x0D:
    name: Latency_Timer
    width: 1
    subField: null
    attribute: RO
0x0E:
    name: Header_Type
    width: 1
    subField: null
    attribute: RO
0x0F:
    name: BIST
    width: 1
    subField: null
    attribute: RO
0x10:
    name: BAR0
    width: 4
    subField: null
    attribute: RO
0x14:
    name: BAR1
    width: 4
    subField: null
    attribute: RO
0x18:
    name: BAR2
    width: 4
    subField: null
    attribute: RO
0x1C:
    name: BAR3
    width: 4
    subField: null
    attribute: RO
0x20:
    name: BAR4
    width: 4
    subField: null
    attribute: RO
0x20:
    name: BAR5
    width: 4
    subField: null
    attribute: RO
0x28:
    name: Cardbus_CIS_Pointer
    width: 4
    subField: null
    attribute: RO
0x2C:
    name: Subsystem_Vendor_ID
    width: 2
    subField: null
    attribute: RO
0x2E:
    name: Subsystem_ID
    width: 2
    subField: null
    attribute: RO
0x30:
    name: Expansion_ROM_Base_Address
    width: 4
    subField: null
    attribute: RO
0x34:
    name: Capability_Pointer
    width: 1
    subField: null
    attribute: RO
0x3C:
    name: Interrupt_Line
    width: 1
    subField: null
    attribute: RO
0x3D:
    name: Interrupt_Pin
    width: 1
    subField: null
    attribute: RO
0x3E:
    name: Min_Gnt
    width: 1
    subField: null
    attribute: RO