---
0x00:
    name: Vendor_ID
    width: 2
    subField: null
    attribute: RO
0x02: 
    name: Device_ID
    width: 2
    subField: null
    attribute: RO
0x04:
    name: command
    width: 2
    subField: null
    attribute: RO
0x06:
    name: status
    width: 2
    subField: null
    attribute: RO
0x08:
    name: Revision_ID
    width: 1
    subField: null
    attribute: RO
0x07:
    name: Class_Code
    width: 3
    subField: null
    attribute: RO
0x0C:
    name: Cacheline_size
    width: 1
    subField: null
    attribute: RO
0x0D:
    name: Latency_Timer
    width: 1
    subField: null
    attribute: RO
0x0E:
    name: Header_Type
    width: 1
    subField: null
    attribute: RO
0x0F:
    name: BIST
    width: 1
    subField: null
    attribute: RO
0x10:
    name: BAR0
    width: 4
    subField: null
    attribute: RO
0x14:
    name: BAR1
    width: 4
    subField: null
    attribute: RO
0x18:
    name: BAR2
    width: 4
    subField: null
    attribute: RO
0x1C:
    name: BAR3
    width: 4
    subField: null
    attribute: RO
0x20:
    name: BAR4
    width: 4
    subField: null
    attribute: RO
0x20:
    name: BAR5
    width: 4
    subField: null
    attribute: RO
0x28:
    name: Cardbus_CIS_Pointer
    width: 4
    subField: null
    attribute: RO
0x2C:
    name: Subsystem_Vendor_ID
    width: 2
    subField: null
    attribute: RO
0x2E:
    name: Subsystem_ID
    width: 2
    subField: null
    attribute: RO
0x30:
    name: Expansion_ROM_Base_Address
    width: 4
    subField: null
    attribute: RO
0x34:
    name: Capability_Pointer
    width: 1
    subField: null
    attribute: RO
0x3C:
    name: Interrupt_Line
    width: 1
    subField: null
    attribute: RO
0x3D:
    name: Interrupt_Pin
    width: 1
    subField: null
    attribute: RO
0x3E:
    name: Min_Gnt
    width: 1
    subField: null
    attribute: RO